[project]
name = "metal-ansys-linux-test"
version = "0.1.0"
description = "Testing Quantum Metal and Ansys on Linux"
readme = "README.md"
requires-python = ">=3.11,<3.13"
dependencies = [
    "ipykernel>=7.1.0",
    "jupyterlab>=4.5.0",
    "pyvista>=0.46.4",
    "pyaedt<0.24.0", # Pinned because 0.24.0 breaks things.  
    "squadds>=0.4.3",
    # Local packages
    "quantum-metal",
    "pyEPR-quantum",
]

[tool.ty.src]
exclude = [
    "**/*.py*",
    "**/*.ipynb",
]


[tool.uv.sources]
    quantum-metal = { path = "packages/qiskit-metal", editable = true }
    pyEPR-quantum = { path = "packages/pyEPR", editable = true }
    # squadds = { path = "packages/SQuADDS", editable = true } # Using published release

